apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "core-provider.fullname" . }}-rbac-configmap
data:
  serviceaccount.yaml: |
{{ tpl (.Files.Get "assets/cdc/rbac/serviceaccount.yaml") . | indent 4 }}
  clusterrole.yaml: |
{{ tpl (.Files.Get "assets/cdc/rbac/clusterrole.yaml") . | indent 4 }}
  clusterrolebinding.yaml: |
{{ tpl (.Files.Get "assets/cdc/rbac/clusterrolebinding.yaml") . | indent 4 }}
  compositiondefinition-role.yaml: |
{{ tpl (.Files.Get "assets/cdc/rbac/compositiondefinition-role.yaml") . | indent 4 }}
  compositiondefinition-rolebinding.yaml: |
{{ tpl (.Files.Get "assets/cdc/rbac/compositiondefinition-rolebinding.yaml") . | indent 4 }}
  secret-role.yaml: |
{{ tpl (.Files.Get "assets/cdc/rbac/secret-role.yaml") . | indent 4 }}
  secret-rolebinding.yaml: |
{{ tpl (.Files.Get "assets/cdc/rbac/secret-rolebinding.yaml") . | indent 4 }}