apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "core-provider.fullname" . }}-cdc-deployment
  labels:
    {{- include "core-provider.labels" . | nindent 4 }}
data:
    deployment.yaml: |
{{ tpl (.Files.Get "assets/cdc/deployment.yaml") . | indent 6 }}