apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "core-provider.fullname" . }}-cdc-configmap
  labels:
    {{- include "core-provider.labels" . | nindent 4 }}
data:
  configmap.yaml: |
{{ tpl (.Files.Get "assets/cdc/configmap.yaml") . | indent 4 }}
