apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "core-provider.fullname" . }}
  labels:
    {{- include "core-provider.labels" . | nindent 4 }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": pre-install, pre-upgrade
    "helm.sh/hook-weight": "2"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    spec:
      restartPolicy: OnFailure
      serviceAccount: {{ include "core-provider.fullname" . }}-job-sa
      containers:
        - name: {{ include "core-provider.fullname" . }}-patcher
          image: ghcr.io/krateoplatformops/kubectl:1.32.0
          command: ['/bin/bash','/tmp/mount/create-certs.sh', {{ .Release.Namespace }},  "{{ include "core-provider.fullname" . }}-webhook-service"]
          volumeMounts:
            - name: script-volume
              mountPath: /tmp/mount
      volumes:
        - name: script-volume
          configMap:
            name: {{ include "core-provider.fullname" . }}-script-configmap
