apiVersion: v1
kind: Service
metadata:
  name: core-provider-webhook-service
  labels:
    {{- include "core-provider.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 9443
      targetPort: 9443
      protocol: TCP
  selector:
    {{- include "core-provider.selectorLabels" . | nindent 4 }}
