apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{`{{ .resource }}`}}-{{`{{ .apiVersion }}`}}
rules:
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["get", "list"]
- apiGroups: ["composition.krateo.io"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["roles", "rolebindings", "clusterroles", "clusterrolebindings"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list", "watch", "create"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "create", "delete", "update"]
- apiGroups: ["core.krateo.io"]
  resources: ["compositiondefinitions", "compositiondefinitions/status"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch", "update"]