apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{`{{ .resource }}`}}-{{`{{ .apiVersion }}`}}
  namespace: {{`{{ .namespace }}`}}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "create", "delete", "update"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch", "update"]
- apiGroups: ["core.krateo.io"]
  resources: ["compositiondefinitions", "compositiondefinitions/status"]
  verbs: ["get", "list", "watch"]