apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{`{{ .resource }}`}}-{{`{{ .apiVersion }}`}}-secret
  namespace: {{`{{ .namespace }}`}}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch"]
  resourceNames: ["{{`{{ .secretName}}`}}"]