apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "core-provider.fullname" . }}
webhooks:
- name: core.provider.krateo.io
  admissionReviewVersions:
    - v1
    - v1alpha2
    - v1alpha1
  rules:
    - operations: ["CREATE", "UPDATE"]
      apiGroups: ["composition.krateo.io"]
      apiVersions: ["*"]
      resources: ["*"]
      scope: "*"
  sideEffects: None
  clientConfig:
    service:
      namespace: {{ .Release.Namespace }}
      name: {{ include "core-provider.fullname" . }}-webhook-service
      path: /mutate
      port: 9443
    caBundle: {{`{{ .caBundle }}`}}