apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "chart-inspector.fullname" . }}-{{ .Release.Namespace }}
  labels:
    {{- include "chart-inspector.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "chart-inspector.fullname" . }}-{{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: {{ include "chart-inspector.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}